/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/model/officetable.glb 
Author: Agha.Najam (https://sketchfab.com/Agha.Najam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-table-80130830a9814e9298f11920ad0b7275
Title: Office Table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/officetable.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.BASE} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.METAL} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.METAL} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.BASE} />
    </group>
  )
}

useGLTF.preload('/officetable.glb')
